# -*- coding: utf-8 -*-
"""Exercices Objets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BE5CrsuLnu9LEnsACPcWSAM26ZMWyBUg

Exercice Compte Bancaire
"""

class compteBancaire:
  def __init__(self, prenom, nom, solde):
    self.prenom = prenom
    self.nom = nom
    self.solde = solde
  def retrait(self, somme):
    self.solde -= somme
  def depot(self, somme):
    self.solde += somme
  def affiche(self):
    print("Le solde du compte en banque de {} {} est de {}".format(self.prenom, self.nom, self.solde))

print("Bonjour,")
compte1 = compteBancaire("Corentin","Brilland", 3900)
compte1.depot(250)
compte1.retrait(75)
compte1.affiche()
compte2 = compteBancaire("Phillipe", "Bénille", 1000)
compte2.depot(50)
compte2.affiche()

"""Exercice Surcharge d'opérateur"""

class Point:
  def __init__(self, a, b, c=0):
    self.a = float(a)
    self.b = float(b)
    self.c = c
  
  def ToString(self):
    print("P({}, {}, {})".format(self.a, self.b, self.c))
  def ToString(self):
    print("P({}, {})".format(self.a, self.b))
P1 = Point(1, -2, 5)
P1.ToString()
P2 = Point(1, 2)
P2.ToString()

