# -*- coding: utf-8 -*-
"""Exercice 1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWcxR8qV2z2Asb6K-ciPJIWuVUTIajs4
"""

nombreSTR=input()
nombre = int(nombreSTR)
type(nombre)
if nombre > 0:
  print("Ce chiffre est positif")
elif nombre < 0:
  print("ce chiffre est négatif")
else:
  print("Le 0 ne compte pas ici")

