# -*- coding: utf-8 -*-
"""Exo data science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHXL5YIkSD1VI4jjlHv3JfBnHlBHM32h
"""

import pandas as pd
import numpy as np
import seaborn as sns
print("Importé")

from google.colab import drive
drive.mount('/content/gdrive')

df=pd.read_csv('gdrive/My Drive/Python/Data/Copie de sales_predictions.csv')
df.head(5)
df1 = df.sample(50)
df1.date = pd.to_datetime(df.date)

graphique = sns.relplot(x="date", y="item_price", data=df1)
#graphique = sns.catplot(x="Attrition", y="JobSatisfaction", data=df)

